# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "OSCONF Hyderabad 2020"
email: "contact@collabnix.com"
description: "OSCONF Hyderabad 2020 - Online Conference"
baseurl: "/osconf-hyd"
url: "http://osconf-hyd.collabnix.com/"
#permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""
github_username: inovizz

# Organizer Info
organizerName: "Collabnix Community"
organizerAlternateName: "Collabnix"
organizerDescription: "Collabnix"
organizerEmail: "contact@collabnix.com"
organizerLogo: "/img/collabnix.png"
organizerLink: "https://collabnix.com"

# Head
metaKeywords: "conference, collabnix, osconfhyd, osconf, docker, kubernetes, cloud, developers, devops, sre"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
#  - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
#  - {permalink: "/logistics/", text: "Logistics"}
#  - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://forms.gle/y2PFj8cdFxW5bud2A", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://forms.gle/y2PFj8cdFxW5bud2A", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "OSCONF </br> <span>HYDERABAD</span> 2020"
eventDate: "1st Aug, 9:00-16:00 IST"
typeoutTextValues: 'OSCONF", "India"'
typeoutFallback: ""
heroButtons:
 - {link: "https://www.papercall.io/osconfhyd2020", text: "Become a Speaker"}
 - {link: "https://forms.gle/y2PFj8cdFxW5bud2A", text: "Register"}

# About Block
aboutTitle: "About OSCONF Hyderabad"
aboutBlock:
 - {title: "", image: "conference.jpg", text: "OSCONF is a platform built to connect & bring all leading Meetup communities, Cloud native experts, Evangelists & DevOps together under one roof. It is a non-profit community event which allows you to interact with community leaders, ambassadors & open community contributors." }


# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Online"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "YouTube Live Stream"
# eventAddressLocality: "Lviv"
# eventAddressLocalityRegion: "Lvivska"
# eventPostalCode: "79000"
# eventAddressCountry: "Ukraine"
eventStartTime: "2020-08-01T09:00"
eventDoorTime: "09:00"
eventEndTime: "2020-08-01T16:30"
eventPlaceCoordinates: "17.3850, 78.4867"
mapCenterCoordinates: "17.3850, 78.4867"
mapMobileCenterCoordinates: "17.3850, 78.4867"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "osconfhyd2020"
twitterFeed: "https://twitter.com/osconfevent?ref_src=twsrc%5Etfw"

# Partners Block
organizersTitle: "Organizers"
# partnersTitle: "Partners"
# partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
# subscribeImage: "subscribe.jpg"
# subscribeTitle: "Subscribe for updates"
# subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
# subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"


# Footer
socialLinks:
 - {link: "https://www.linkedin.com/company/collabnix/", icon: "linkedin"}
 - {link: "https://twitter.com/osconfevent", icon: "twitter"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://collabnix.com", text: "Collabnix"}
   - {link: "https://osconf.collabnix.com/", text: "OSCONF"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:contact@collabnix.com", text: "contact@collabnix.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
# blogTitle: "Latest news"
# blogCommentsEnabled: true
# discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "OSCONF is a platform built to connect & bring all leading Meetup communities, Cloud native experts, Evangelists & DevOps together under one roof. It is a non-profit community event which allows you to interact with community leaders, ambassadors & open community contributors."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false
